# Generated by Django 2.0.7 on 2018-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_actor_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('film', 'Film'), ('tv', 'TV'), ('ftv', 'FTV')], default='film', max_length=32),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
