# Generated by Django 2.0.7 on 2018-08-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20180811_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='place_of_birth',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='role',
            field=models.ManyToManyField(to='movie.Role'),
        ),
    ]
