# Generated by Django 2.0.7 on 2018-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20180812_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='role',
            field=models.ManyToManyField(null=True, to='movie.Role'),
        ),
    ]
