# Generated by Django 2.0.7 on 2018-08-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20180812_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='actor',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Location'),
        ),
    ]
