# Generated by Django 2.1 on 2018-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20180812_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='role',
            field=models.ManyToManyField(to='movie.Role'),
        ),
    ]
